---
title: "Assignment 1: Introduction"
author: "Laura Exar"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex
Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.
```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex()
```

### Set your default knit directory
This setting will help deal with relative paths later on...
 - From the Tool menu, select `Global Options`
 - Select the RMarkdown section
 - In the "Evaluate chunks in directory", set the option to "Project"


## 2) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: My experience with data analytics is very limited, and was touched on in a few courses in undergrad. In my undergrad, I worked on a research project for three semesters where we used R Studio, but that was several years ago so I am out of practice. The training for this project was fairly informal (my research professor would just tell us how to do different steps), and I took one more formal class on statistics and R Studio. I have never used Git.

2. Are there any components of the course about which you feel confident?

> Answer: I generally feel pretty confident about the components of this course, and I think I will remember how to use R Studio from my previous experience. I have also heard very good things about this course from past students, which makes me excited for the course to start and also feel more confident about the different aspects of it.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I'm apprehensive about figuring out Git, as well as a little apprehensive about the format of a flipped classroom course in general. I'm worried I'll miss something! I'm also worried my laptop won't make it through the semester, but I chose the "container" option so hopefully I'm prepared if anything happens!


## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/lauraexar/EDA-Spring2023

## 4) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
